services:
  cronicle:
    image: bluet/cronicle-docker:latest
    container_name: cronicle
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "3012:3012"
    volumes:
      - cronicle_data:/opt/cronicle/data
    healthcheck:
      disable: false

volumes:
  cronicle_data:
    name: cronicle_data
