services:
    cronicle:
        image: bluet/cronicle-docker:latest
        container_name: cronicle
        user: root:root
        hostname: cronicle
        restart: unless-stopped
        network_mode: host
        environment:
            - TZ=${TIMEZONE}
            - CRONICLE_smtp_hostname=${SMTP_HOSTNAME}
            - CRONICLE_smtp_port=${SMTP_PORT}
            - CRONICLE_email_from=${SMTP_EMAIL}
            - CRONICLE_mail_options__auth__user=${SMTP_EMAIL}
            - CRONICLE_mail_options__auth__pass=${SMTP_GMAIL_APP_PASSWORD}
        ports:
            - "3012:3012"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${DATA_DIR}/cronicle/data:/opt/cronicle/data
            - ${DATA_DIR}/cronicle/logs:/opt/cronicle/logs
            - ${DATA_DIR}/cronicle/plugins:/opt/cronicle/plugins
            - ${DATA_DIR}/cronicle/ssh:/opt/cronicle/ssh
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:3012/ || exit 1"]
            interval: 15s
            timeout: 5s
            retries: 5
