services:
    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - grafana_data:/var/lib/grafana
        depends_on: [prometheus]

    prometheus:
        container_name: prometheus
        network_mode: "host"
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ../config/prometheus.config.yml:/etc/prometheus/prometheus.yml:ro
            - prometheus_data:/prometheus

    node_exporter:
        container_name: node_exporter
        image: prom/node-exporter:latest
        pid: "host"
        network_mode: "host"
        command: ["--collector.systemd", "--collector.processes"]
        restart: unless-stopped


    cadvisor:
        container_name: cadvisor
        image: gcr.io/cadvisor/cadvisor:latest
        network_mode: "host"
        pid: "host"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        restart: unless-stopped

volumes:
    grafana_data:
        name: grafana_data
    prometheus_data:
        name: prometheus_data
