services:
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        user: root:root
        network_mode: "host"
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
        volumes:
            - ${HOME}/homelab/volumes/grafana/data:/var/lib/grafana
        depends_on: [prometheus]

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        user: root:root
        network_mode: "host"
        restart: unless-stopped
        ports:
            - "9090:9090"
        volumes:
            - ${HOME}/homelab/config/prometheus.config.yml:/etc/prometheus/prometheus.yml:ro
            - ${HOME}/homelab/volumes/prometheus/data:/prometheus

    node-exporter:
        image: prom/node-exporter:latest
        container_name: node-exporter
        user: root:root
        pid: "host"
        network_mode: "host"
        command: ["--collector.systemd", "--collector.processes"]
        restart: unless-stopped
