services:
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        user: root:root
        network_mode: "host"
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
        volumes:
            - ${BASE_DIR}/volumes/grafana/data:/var/lib/grafana
        depends_on: [prometheus]
        healthcheck:
            test: ["CMD", "nc", "-z", "0.0.0.0", "3000"]
            interval: 15s
            timeout: 5s
            retries: 5

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        user: root:root
        network_mode: "host"
        restart: unless-stopped
        ports:
            - "9090:9090"
        volumes:
            - ${BASE_DIR}/config/prometheus.config.yml:/etc/prometheus/prometheus.yml:ro
            - ${BASE_DIR}/volumes/prometheus/data:/prometheus
        healthcheck:
            test: ["CMD", "nc", "-z", "0.0.0.0", "9090"]
            interval: 15s
            timeout: 5s
            retries: 5

    node-exporter:
        image: prom/node-exporter:latest
        container_name: node-exporter
        user: root:root
        pid: "host"
        network_mode: "host"
        command: ["--collector.systemd", "--collector.processes"]
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "nc", "-z", "0.0.0.0", "9100"]
            interval: 15s
            timeout: 5s
            retries: 5
