services:
    minecraft-server:
        image: itzg/minecraft-server
        container_name: minecraft-server
        user: root:root
        restart: unless-stopped
        tty: true
        stdin_open: true
        ports:
            - "25565:25565"
        environment:
            EULA: ${MINECRAFT_EULA}
            MEMORY: ${MINECRAFT_MEMORY}
        volumes:
            - ${VOLUMES_DIR}/minecraft/data:/data
        healthcheck:
            test: ["CMD-SHELL", "nc -z localhost 25565 || exit 1"]
            interval: 15s
            timeout: 5s
            retries: 5
