services:
    minecraft-server:
        image: itzg/minecraft-server
        container_name: minecraft-server
        user: root:root
        restart: unless-stopped
        tty: true
        stdin_open: true
        ports:
            - "25565:25565"
        environment:
            EULA: ${MINECRAFT_EULA}
            MEMORY: ${MINECRAFT_MEMORY}
        volumes:
            - ${HOME}/homelab/volumes/minecraft/data:/data
