services:
    minecraft-server:
        image: itzg/minecraft-server
        container_name: minecraft-server
        profiles: ["disabled"]
        user: root:root
        restart: unless-stopped
        tty: true
        stdin_open: true
        ports:
            - "25565:25565"
        environment:
            EULA: ${MINECRAFT_EULA}
            MEMORY: ${MINECRAFT_MEMORY}
        volumes:
            - ${HOME}/homelab/volumes/minecraft/data:/data
        healthcheck:
            test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/25565"]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 30s
