services:
    minecraft-server:
        container_name: minecraft-server
        image: itzg/minecraft-server
        tty: true
        stdin_open: true
        ports:
            - "25565:25565"
        environment:
            EULA: "TRUE"
            MEMORY: "2048M"
        volumes:
            # attach the relative directory 'data' to the container's /data path
            - minecraft_data:/data

volumes:
    minecraft_data:
        name: minecraft_data

