services:
    tailscale:
        image: tailscale/tailscale:latest
        container_name: tailscale
        user: root:root
        restart: unless-stopped
        network_mode: "host"
        privileged: true
        cap_add:
            - NET_ADMIN
            - NET_RAW
        environment:
            TS_AUTHKEY: "${TAILSCALE_AUTHKEY}"
            TS_DNS: "${TAILSCALE_DNS}"
        volumes:
            - ${HOME}/homelab/volumes/tailscale/data:/var/lib/tailscale
            - /dev/net/tun:/dev/net/tun
        healthcheck:
            test: ["CMD-SHELL", "tailscale status || exit 1"]
            interval: 15s
            timeout: 5s
            retries: 5
