services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    env_file:
      - ../.env
    environment:
      TS_AUTHKEY: "${TS_AUTHKEY}"
      TS_DNS: "${TS_DNS}"
    volumes:
      - tailscale_state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun

volumes:
  tailscale_state:
    name: tailscale_state

