services:
    tailscale:
        image: tailscale/tailscale:latest
        container_name: tailscale
        restart: unless-stopped
        network_mode: "host"
        privileged: true
        cap_add:
            - NET_ADMIN
            - NET_RAW
        env_file:
            - ../.env
        environment:
            TS_AUTHKEY: "${TAILSCALE_AUTHKEY}"
            TS_DNS: "${TAILSCALE_DNS}"
        volumes:
            - ${HOME}/homelab/volumes/tailscale/data:/var/lib/tailscale
            - /dev/net/tun:/dev/net/tun
        healthcheck:
            disable: false
