server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: authlog
    static_configs:
      - targets: [localhost]
        labels:
          job: authlog
          __path__: /var/log/auth.log

  - job_name: syslog
    static_configs:
      - targets: [localhost]
        labels:
          job: syslog
          __path__: /var/log/syslog


  - job_name: ufw
    static_configs:
      - targets: [localhost]
        labels:
          job: ufw
          __path__: /var/log/ufw.log

  - job_name: kernel
    static_configs:
      - targets: [localhost]
        labels:
          job: kernel
          __path__: /var/log/kern.log
