services:
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: always
        labels:
            - pause_for_backup=false
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${DATA_DIR}/portainer:/data
        ports:
            - "9443:9443"
        env_file:
            - /etc/homelab/.env
