services:
    dockhand:
        image: fnsys/dockhand:latest
        container_name: dockhand
        restart: unless-stopped
        user: root:root
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${DATA_DIR}/dockhand:/app/data
        ports:
            - 4000:3000
