name: CI and Deploy

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        types: [opened, synchronize, reopened]

jobs:
    test:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run Install Script
              working-directory: ${{ github.workspace }}
              env:
                  DOPPLER_PROJECT: ${{ secrets.DOPPLER_PROJECT }}
                  DOPPLER_CONFIG: ${{ secrets.DOPPLER_CONFIG }}
                  DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
              run: |
                  sudo -E ./scripts/install.sh

            - name: Run Prepare Script
              working-directory: ${{ github.workspace }}
              env:
                  DOPPLER_PROJECT: ${{ secrets.DOPPLER_PROJECT }}
                  DOPPLER_CONFIG: ${{ secrets.DOPPLER_CONFIG }}
                  DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
              run: |
                  sudo -E ./scripts/prepare.sh

            - name: Run Backup Script
              working-directory: ${{ github.workspace }}
              env:
                  DOPPLER_PROJECT: ${{ secrets.DOPPLER_PROJECT }}
                  DOPPLER_CONFIG: ${{ secrets.DOPPLER_CONFIG }}
                  DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
              run: |
                  sudo -E ./scripts/backup.sh

    deploy:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Connect Tailscale
              uses: tailscale/github-action@v3
              with:
                  authkey: ${{ secrets.TAILSCALE_CI_AUTHKEY }}
                  statedir: /tmp/tailscale-state/

            - name: Deploy to server
              run: |
                  curl -s http://homelab:5001/tasks/run/deploy

            - name: Wait for heartbeat
              run: |
                  echo "Waiting 60s..."
                  sleep 60

            - name: Check server health
            - run: |
                  status_code=$(curl -s -o /dev/null -w "%{http_code}" http://homelab:5001)

                  if [ "$status_code" -ne 200 ]; then
                      echo "Deployment health check failed: HTTP $status_code"
                      exit 1
                  else
                      echo "Deployment succeeded."
                      exit 0
                  fi
