name: Homelab CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:  # optional manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Build & start containers
      - name: Start services
        run: |
          ./scripts/start-services.sh .test.env

      # 4. Healthcheck
      - name: Run Healthcheck
        run: |
          ./scripts/healthcheck.sh .test.env

      # 5. Tear down test containers
      - name: Tear down
        run: |
          ./scripts/stop-services.sh .test.env

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ secrets.SSH_PRIVATE_KEY && secrets.SSH_USER && secrets.SSH_HOST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH agent
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # SSH into server and deploy
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/homelab

            # Pull latest code
            git fetch --all
            git reset --hard origin/main

            # Optional: stop services before deployment
            ./scripts/stop-services.sh

            # Start services
            ./scripts/start-services.sh

          EOF
